spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/twisub
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085
