spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notifier_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.jstructure.twisub.notifier.serializer.TweetsDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

app:
  email-sender-url: http://localhost:8084
  notifications-url: http://localhost:8086

server:
  port: 8087
