spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notifier_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

app:
  email-sender-url: http://localhost:8084
  users-url: http://localhost:8085
